name: Continous Integration for Node app

on:
  push:
    branches:
      - '*
jobs:
  continous-Integration-to-build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push the Golang Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: sidharthpai/golang_rest:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}
